### ISSUE TITLE
Check for duplicate group names

### ISSUE THREAD

**Issue by sbrp** [lwsrbrts/PoSHue#16]
When creating a new group, no checks are done to make sure there isn't a group already existing with the same name. So you could end up in this situation after running $Group.GetLightGroups()

25 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
26 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
27 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
28 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
29 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
30 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
31 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
32 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
33 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}

**Comment by lwsrbrts** [comment]
Just to confirm this is a wontfix - purely because it should be possible to create duplicate group names when the groups are of the LightGroup type. This is something permitted by the bridge - it doesn't care if all your LightGroups are called "My Group" since it uses the group's ID number to interact with the group.

The latest commit introduces the ability to instantiate a HueGroup object using the group's ID number as well as its name - this bypasses the "duplicate name" issue.

Thanks for the issue!
