### ISSUE TITLE
Control light groups

### ISSUE THREAD

**Issue by ghost** [lwsrbrts/PoSHue#4]
How to control groups of lights with your script?

e.g this is the line for getting a single light. What is the equivalent for a group

$Office = [HueLight]::new("Living", $Endpoint, $UserID)

**Comment by lwsrbrts** [comment]
@davebanthorpe that'll have to be the recalling of a scene for now I'm afraid. Unfortunately I haven't implemented the groups API yet. I'm sure it will come as I have acquired a lot more lights in recent months.

**Comment by lwsrbrts** [comment]
Now in progress.

**Comment by lwsrbrts** [comment]
I've created the basic control features of the Group class now and it's usable.

There are two constructors for HueGroup. You may only want to create a group rather than control an existing one. This first example is to just get a blank HueGroup object, allowing you to create or delete an existing group.
```powershell
$Group = [HueGroup]::new('192.168.1.12', 'myapikey')
```

This example create a HueGroup object and obtains some information about a group or room called "Living room"

```powershell
$Group = [HueGroup]::new('Living room', '192.168.1.12', 'myapikey')
```

You can now:

- List groups on the Bridge
  - GetLightGroups()
- Create groups (two types, "Rooms" and "Light Groups". Lights can only be a member of one room. Lights can be a member of multiple Light Groups.
  - CreateLightGroup([string]$GroupName, [string[]] $LightID) - creates  a simple Light Group
  - CreateLightGroup([string]$GroupName, [RoomClass]$RoomClass, [string[]] $LightID) - creates a Room. The RoomClass is a list of names which must be one of
   Kitchen
   Dining
    Bedroom
    Bathroom
    Nursery
    Recreation
    Office
    Gym
    Hallway
    Toilet
    Garage
    Terrace
    Garden
    Driveway
    Carport
    Other
- Delete a group or room
  - DeleteLightGroup([string]$GroupName)
- Switch a group of lights/room on or off using any of
  - SwitchHueGroup()
  - SwitchHueGroup([LightState] $State)
  - SwitchHueGroup([LightState] $State, [bool] $Transition)

**Comment by lwsrbrts** [comment]
I've updated the PowerShell Gallery module as 1.1.1 and the documentation for the above. Additional tinkering will complete Groups API support with changing brightness, colour, saturation, xy etc. in the next couple of weeks - that will be version 1.1.2.

If you installed from the gallery, running: `Update-Module -Name PoSHue` will get you 1.1.1 now and 1.1.2 when that's released. I'll hold off doing a release in GitHub for now until 1.1.2 is ready to go.

1.1.1 Gives you create, edit, delete and state (on/off) control of groups. Rooms and LightGroups are supported.

Lewis

**Comment by lwsrbrts** [comment]
Now complete and 1.1.2 has been released to the PowerShell Gallery.
