### ISSUE TITLE
Question about using this module over the internet

### ISSUE THREAD

**Issue by Raipel** [lwsrbrts/PoSHue#7]
Hello,
I want to use this module over the internet. First when an event was triggered, a Windows Server (out my house) entrerd a pssession to my homeserver and this homeserver turned the Lights on. But this solution was to slow (20 seconds) for me. Because of the slowness I tried to start the script at the Windows server (not in my house). And the Windows server uses the PoShue Module. The $HueIP was the DynDNS address of my home. I have the worry, that the connection isn't secure because it communicates with port 80. Please tell me if the connection to the Bridge is encrpyted?

Thank you very much
Sorry for my bad english
Raipel

**Comment by lwsrbrts** [comment]
Hi @raipel to answer your question: no, the connection to the bridge is not encrypted in that scenario.

The module is an abstraction of the Hue APIs offered in PowerShell, allowing you to script actions. It doesn't use encryption because the bridge doesn't require it.

I personally wouldn't make the Hue Bridge available to the Internet as any flaws it may have could be exposed by a bad actor, giving them the ability to mess up the configuration, turn lights on and off or brick the bridge completely.

You could use a VPN between your server and home instead.

Something else to consider now is that the module works with PowerShell Core 6.0 which means it works on Linux, Mac and other platforms such as Raspberry Pi.

**Comment by lwsrbrts** [comment]
FYI, the module now supports Philips' new (this week) Remote API that means you can use the bridge securely via the internet. check out the readme on the project page for a link to a video explaining the process.

**Comment by lwsrbrts** [comment]
With the Remote API now supported, this scenario is possible without any additional hardware or configuration.
